name: Sync upstream & patch installer

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add & fetch upstream
        run: |
          git remote add upstream https://github.com/MHSanaei/3x-ui.git || true
          git fetch upstream --tags

      - name: Merge upstream/main
        run: |
          git checkout main
          git merge --no-edit upstream/main

      - name: Patch install.sh
        run: |
          sed -i 's|MHSanaei/3x-ui|tee1975/3x-ui|g' install.sh
          sed -i 's|raw.githubusercontent.com/MHSanaei/3x-ui|raw.githubusercontent.com/tee1975/3x-ui|g' install.sh
          sed -i 's|github.com/MHSanaei/3x-ui|github.com/tee1975/3x-ui|g' install.sh

      - name: Commit & push
        run: |
          git add install.sh
          git diff --cached --quiet || git commit -m "chore: auto-patch installer after upstream sync"
          git push origin main
